site_name: Fenil Patel Portfolio
site_url: https://fenil264.github.io/Fenil_Portfolio/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight

# Custom styling
extra_css:
  - styles/extra.css

# Navigation sidebar
nav:
  - Home: index.md
  - Data Science:
      - Retail Profit Optimization: ds/retail-profit.md
  - Data Analytics:
      - Sales Dashboard: da/sales-dashboard.md
  - Data Engineering:
      - Data Pipeline: de/data-pipeline.md

# GitHub repo link
repo_url: https://github.com/fenil264/Fenil_Portfolio
repo_name: fenil264/Fenil_Portfolio

# Markdown formatting
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
