# === Site configuration ===
site_name: ""  # Intentionally blank to remove sidebar title
site_url: https://fenil264.github.io/Fenil_Portfolio/

# === Theme settings using Material for MkDocs ===
theme:
  name: material

  # Color palette for professional dark theme
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

  # Optional: Add a logo (store it in docs/assets/logo.png)
  # logo: assets/logo.png

  # Header and navigation behavior
  features:
    - navigation.tabs         # Enables top-level tabs (puts Home in header)
    - navigation.sections     # Sidebar grouped by sections
    - navigation.instant      # Instant load without page refresh
    - search.suggest          # Smart search suggestions
    - search.highlight        # Highlights keywords in results

  icon:
    repo: fontawesome/brands/github  # GitHub icon in header

# === Navigation structure (top-level go to header tabs) ===
nav:
  - Home: index.md
  - Data Science:
      - Retail Profit Optimization: ds/retail-profit.md
  - Data Analytics:
      - Sales Dashboard: da/sales-dashboard.md
  - Data Engineering:
      - Data Pipeline: de/data-pipeline.md

# === GitHub repo link ===
repo_url: https://github.com/fenil264/Fenil_Portfolio
repo_name: fenil264/Fenil_Portfolio

# === Markdown enhancements ===
markdown_extensions:
  - admonition               # Blocks for tips, notes, warnings
  - codehilite               # Syntax highlighting
  - footnotes                # Support for footnotes
  - meta                     # Allows metadata in markdown files
  - toc:
      permalink: true        # Adds link icons next to headers

# === Plugins ===
plugins:
  - search

# === Custom styling ===
extra_css:
  - styles/extra.css
