# Site metadata
site_name: Fenil Patel Portfolio
site_url: https://fenil264.github.io/Fenil_Portfolio/

# Theme configuration using Material for MkDocs
theme:
  name: material

  # Color scheme settings
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

  # GitHub icon in the header
  icon:
    repo: fontawesome/brands/github

  # Theme features
  features:
    # Removed navigation.tabs to keep everything in the left sidebar
    - navigation.sections         # Sidebar grouped by sections
    - navigation.instant          # Fast, reload-free page transitions
    - search.suggest              # Auto-suggest while typing
    - search.highlight            # Highlights matched search terms

# Navigation structure (appears in the left sidebar)
nav:
  - Home: index.md
  - Data Science:
      - Retail Profit Optimization: ds/retail-profit.md
  - Data Analytics:
      - Sales Dashboard: da/sales-dashboard.md
  - Data Engineering:
      - Data Pipeline: de/data-pipeline.md  # Remove this line if file doesn't exist

# GitHub repo link in the top-right corner
repo_url: https://github.com/fenil264/Fenil_Portfolio
repo_name: fenil264/Fenil_Portfolio

# Markdown extensions to enhance page formatting
markdown_extensions:
  - admonition               # For notes, tips, and warnings
  - codehilite               # Code syntax highlighting
  - footnotes                # Support for footnotes
  - meta                     # Enable meta tags in markdown files
  - toc:
      permalink: true        # Anchor links beside each heading

# MkDocs plugins
plugins:
  - search
