# ============================
#    Fenil Patel Portfolio
# ============================

# Site Information
site_name: Fenil Patel Portfolio
site_url: https://fenil264.github.io/Fenil_Portfolio/

# Theme: Material for MkDocs
theme:
  name: material

  # Color palette
  palette:
    scheme: slate         # Dark mode look
    primary: indigo       # Brand color
    accent: indigo

  # GitHub icon in top-right
  icon:
    repo: fontawesome/brands/github

  # UI Features
  features:
    - navigation.sections     # Sidebar section groups
    - navigation.instant      # Fast, reload-free navigation
    - search.suggest          # Typeahead search
    - search.highlight        # Highlight results

nav:
  - Home: index.md
  - Data Science:
      - Retail Profit Optimization: ds/retail-profit.md
  - Data Analytics:
      - Sales Dashboard: da/sales-dashboard.md
      - EDA and Data Cleaning: da/eda-cleaning.md
  - Data Engineering:
      - Data Pipeline: de/data-pipeline.md


# GitHub Repository Link
repo_url: https://github.com/fenil264/Fenil_Portfolio
repo_name: fenil264/Fenil_Portfolio

# Markdown Enhancements
markdown_extensions:
  - admonition          # Tip/note blocks
  - codehilite          # Syntax highlighting
  - footnotes           # Markdown footnotes
  - meta                # Metadata in markdown
  - toc:
      permalink: true   # Anchor links on headings

# Plugins for extended features
plugins:
  - search

# Custom CSS (for design and layout)
extra_css:
  - styles/extra.css
