site_name: "Fenil Patel Portfolio"
site_url: https://fenil264.github.io/Fenil_Portfolio/

theme:
  name: material

  palette:
    scheme: slate
    primary: indigo
    accent: indigo

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight

  icon:
    repo: fontawesome/brands/github

nav:
  - Home:
      - Overview: index.md
  - Data Science:
      - Retail Profit Optimization: ds/retail-profit.md
  - Data Analytics:
      - Sales Dashboard: da/sales-dashboard.md
  - Data Engineering:
      - Data Pipeline: de/data-pipeline.md

repo_url: https://github.com/fenil264/Fenil_Portfolio
repo_name: fenil264/Fenil_Portfolio

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - styles/extra.css
